# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="TOTEM"

# Core Features
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_STUDIO=y

# Bluetooth Stability & Safe Reconnection
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_RESET=n
CONFIG_ZMK_SLEEP=n

# Balanced Bluetooth Power (Saves battery compared to +8)
CONFIG_BT_CTLR_TX_PWR_PLUS_4=y

# Battery Reporting for Both Halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
